### ISSUE TITLE
Missing path to file from sourcemaps

### ISSUE THREAD

**Issue by antitoxic** [bySabi/karma-tap-pretty-reporter#15]
My errors come up with: "Name of error  **at undefined**". I assume undefined should be a file path. But I can't get it to work.

I use webpack and karma-sourcemap-loader. Anything special I need to configure?

**Comment by antitoxic** [comment]
A little bit of info:

Outputting `result` in `this.specFailure` shows up as:

```
{ description: 'whaaat',
  success: false,
  log: [ '{\n  "operator": "fail"\n}' ],
  suite: [ '# timing test\n' ],
  time: 9 }
```

There is no info in the result about where the error occurred.

**Comment by bySabi** [comment]
Can you share a repo?

**Comment by bySabi** [comment]
@antitoxic probably it's a upstream problem on `tap-parser` and `source map`. Log come from here: https://github.com/bySabi/karma-tap/blob/master/src/adapter.js#L32

A repo repository could help on subject

**Comment by antitoxic** [comment]
Alright! I'm submitting an issue there. Closing this one for now.
