### ISSUE TITLE
Only failed test

### ISSUE THREAD

**Issue by AStaroverov** [bySabi/karma-tap-pretty-reporter#7]
Can i see only failed tests?

**Comment by bySabi** [comment]
Right now this is not implemented on `karma-tap-pretty-reporter` but I think is more suitable to do on a prettifier package

**Comment by AStaroverov** [comment]
It would be right, if we could use prettifiers in pipe. But we cant :(

**Comment by bySabi** [comment]
If you create your custom prettifier I could add to `karma-tap-pretty-reporter` . 

How you say, we cannot pipe on browsers enviroments.

Maybe we can make this at code level, without using standalone tools, just using something like [tape](https://www.npmjs.com/package/tapa)
Is ther another tool, don´t tested it myself, [subtap](https://github.com/jtlapp/subtap)

**Comment by infernalmaster** [comment]
You can use https://github.com/namuol/tap-difflet

```
    tapReporter: {
      // outputFile: './unit.tap',
      get prettify() { return () => require('tap-difflet')({ pessimistic: true }); },
      separator: '****************************',
    },
```

But you should update this packages to latest versions. And have node version with getters available. I use node 6.0

**Comment by bySabi** [comment]
Why `getters` is needed in this case?

**Comment by infernalmaster** [comment]
You are right, this code can be rewriten more simpler without getters:

```
    tapReporter: {
      // outputFile: './unit.tap',
      prettify: function() { return require('tap-difflet')({ pessimistic: true }); },
      separator: '****************************',
    },
```

Maybe this can be added to README

**Comment by bySabi** [comment]
update README with `Show only failed test` use case.

**Comment by bySabi** [comment]
closed due inactivity.

Feel free to reopen is needed

**Comment by AStaroverov** [comment]
Thanks
